### ISSUE TITLE
Devel::Cover hangs when used with Function::Parameters

### ISSUE THREAD

**Issue by zmughal** [pjcj/Devel--Cover#164] opened 2016-06-09 00:25 UTC
I have a [project](https://github.com/project-renard/curie) that uses @mauke's Function::Parameters dist. However, when I run the test suite with `-MDevel::Cover`, the test scripts run the code, but hang right before the script should exit. My current workaround is to [use PPI to modify the code](https://github.com/project-renard/curie/blob/dcd408767e05cd7efb1a1a585cb97c70cf49d6b1/t/lib/PPIFPXform.pm) before the test coverage is run, but this is unsatisfactory.

I tried to make a small example, but I was not able to replicate the same issue with a short script.

Is this something that can be fixed?

CC: https://github.com/project-renard/curie/issues/120.

**Comment by sdt** [comment] 2017-04-12 11:34
I have a minimal test case for this hanging here: https://github.com/sdt/devel-cover-function-parameters-hang

**Comment by zmughal** [comment] 2017-04-12 20:39
@sdt, excellent work on tracking that down!

I was looking into this problem again in GDB a couple weeks ago and for my codebase, the hanging happens right at the end of the script when Devel::Cover tries to identify the location of the ops that were run, but I ran out of tuits before delving into it further. I don't know if that helps.

**Comment by mauke** [comment] 2017-04-13 19:24
My bad; this issue seems to be solely caused by Function::Parameters. I can reproduce it without Devel::Cover and it apparently hangs in the parser. Feel free to close this issue.

**Comment by mauke** [comment] 2017-04-13 21:31
This is actually a [bug in perl itself](https://rt.perl.org/Public/Bug/Display.html?id=131146):

    perl -MDevel::Cover -e '\&f2; sub f2 { sub f2; }'

**Comment by mauke** [comment] 2017-04-14 11:19
My comment above refers to sdt's hang.

The hang during exit seems to be a different issue. It can be reproduced without Function::Parameters:
```perl
#!perl
use Devel::Cover -silent => 1;

use Types::Standard qw(Str);
use constant MyType => Str;

sub f {
    return MyType if @_;
}
```

Note that `MyType` gets inlined (because it's a constant) and the `Str` object is cyclic (it contains a reference to itself). Maybe Devel::Cover doesn't handle this case?

**Comment by zmughal** [comment] 2017-04-14 17:42
Ah, thanks for that! I see that Devel::Cover is using B::Deparse without the Data::Dumper option (`-d`) that you mention at <https://github.com/mauke/Function-Parameters/issues/29#issuecomment-294137390>.

I made a very simple module to force B::Deparse to use Data::Dumper for constants and loaded it using `HARNESS_PERL_SWITCHES`:

```perl
package DeparseDumper;
BEGIN {
	require B::Deparse;
	*B::Deparse::const = \&B::Deparse::const_dumper;
}
1;
```

```shell
export HARNESS_PERL_SWITCHES="-MDevel::Cover -I. -MDeparseDumper"; prove -lvr t
```

**Comment by mohawk2** [comment] 2018-07-26 20:47
I tried @zmughal 's method, which worked great. I wanted to find a way that didn't involve needing the `.pm` file. Putting its contents directly as `-e` type content didn't work, possibly because directly reassigning the sub's contents is "too late" in some fashion. However, this did work:

```
HARNESS_PERL_SWITCHES='-M"5; BEGIN{require B::Deparse; *B::Deparse::const = sub { goto &B::Deparse::const_dumper; }}" -MDevel::Cover' make test
```

Note that using an actual `-e` doesn't work, because again it seems to happen too late. Only the bodgy `-M"5; perl_code_here();"` form worked.

**Comment by mohawk2** [comment] 2018-08-09 17:16
A lesson learned in trying to fix this so far: the tests in `t/e2e` are generated from the files in `tests/`. Such generating then also needs a file in `test_output/cover/` to be created using the `create_gold` utility. One way to iterate this:

```
# can set vars just once, obviously
PERLVER=$(perl -e 'print $]')
NEWTEST=circular_ref
make gold TEST=$NEWTEST && mv test_output/cover/$NEWTEST.$PERLVER test_output/cover/$NEWTEST.5.010000 && make test TEST_FILES=t/e2e/a$NEWTEST.t
```

The above should probably be noted in the docs somewhere.

Also, this is sufficient to make the above hang as the contents of `circular_ref`:

```
#!/usr/bin/perl

my $VAR1;
BEGIN { $VAR1 = \$VAR1 }
use constant MyType => $VAR1;

sub f {
    return MyType if @_;
}
```

My intent is to make the built-in constant-handler `croak` on already-seen refs, and add an option `use_dumper` to do @zmughal's clever hack "properly". A stretch goal will be to make the built-in code handle circular refs itself.

**Closed** 2018-09-18 19:09 UTC
Labels: status: waiting for fix

**Comment by pjcj** [comment] 2018-09-18 19:16
Thank you all so much for this - for the reporting, the detective work and for the fix! This is now merged and will be in the next release.  There are a few output changes but I think it's all good.

I especially appreciate the additional test, and updates to existing test results, even though the test suite is somewhat opaque.

Everyone who wasn't already in the Contributors file has now been added, so if you'd like your entry changed or removed, please either let me know or make a pull request.

Thanks again!
