### ISSUE TITLE
Deep recursion

### ISSUE THREAD

**Issue by philiprbrenan** [pjcj/Devel--Cover#285] opened 2021-06-05 14:18 UTC
I am getting a deep recursion message when running with test cover after all my tests have passed:
```
./Build testcover
test.pl .. 217/254 15:15:38 Success:  9.64 seconds                                                  at /home/phil/perl/cpan/TreeMulti/lib/Tree/Multi.pm line 2716
Deep recursion on subroutine "B::Deparse::deparse" at /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/Devel/Cover.pm line 1005.
test.pl .. All 254 subtests passed 

Test Summary Report
-------------------
test.pl (Wstat: 139 Tests: 254 Failed: 0)
  Non-zero wait status: 139
Files=1, Tests=254, 22 wallclock secs ( 0.04 usr  0.00 sys + 13.74 cusr  0.23 csys = 14.01 CPU)
Result: FAIL
Failed 1/1 test programs. 0/254 subtests failed.
```

**Comment by larryl** [comment] 2021-11-04 23:08
Also getting a deep recursion error that seems to be caused by `__SUB__`.

Using:
Perl v5.34.0
Devel::Cover 1.36
Data::Dumper 2.179

[devel-cover-output.txt](https://github.com/pjcj/Devel--Cover/files/7479377/devel-cover-output.txt)
[devel-cover-recursion.t.txt](https://github.com/pjcj/Devel--Cover/files/7479378/devel-cover-recursion.t.txt)

**Comment by pjcj** [comment] 2022-06-04 15:09
Fixed with https://github.com/pjcj/Devel--Cover/pull/290 - thank you for the report and test case!

**Closed by pjcj** 2022-06-04 15:09 UTC
