### ISSUE TITLE
feature request: exclude branch coverage from perl CORE macros in XS

### ISSUE THREAD

**Issue by Tux** [pjcj/Devel--Cover#234] opened 2019-02-10 10:52 UTC
Each use of e.g. `SAVETMPS` will cause a branch coverage report. I'd like an option to skip all core macro's that are expected not to have an if/else check

**Comment by pjcj** [comment] 2019-04-26 16:07
In discussion with Tux at PTS2019 we have fixed a bug in gcov parsing, decided that we should move to gcov -i output, and decided to leave this as a low-priority wishlist item because it's going to be *hard*.

**Comment by pjcj** [comment] 2019-04-27 10:33
I think this is s duplicate of #214 so I'm going to close this ticket.

**Closed by pjcj** 2019-04-27 10:33 UTC
Labels: prio: wish
