### ISSUE TITLE
condition coverage changes with shortened expressions

### ISSUE THREAD

**Issue by tomk3003** [pjcj/Devel--Cover#201] opened 2017-12-13 12:18 UTC
I have problems with cover reporting unreached conditions when I use expressions like:

    $value = $cond1 || $cond2;

instead of:

    $value = $cond1; $value ||= $cond2;

the coverage report for this looks like this:

    line  err      %      l  !l&&r !l&&!r   expr
    ----- --- ------ ------ ------ ------   ----
    13    ***     66      2      0      2   $c->[0] || $c->[1]
    22           100      2      1      1   $val ||= $c->[1]

I was not able to mask this with an `# uncovered ...` directive.

Thomas
[Uploading cover.txt…]()

**Comment by tomk3003** [comment] 2017-12-13 12:21
The upload didn't work, second try.
[cover.txt](https://github.com/pjcj/Devel--Cover/files/1555429/cover.txt)

**Comment by ikg1hd** [comment] 2018-03-14 07:56
Hi,
I cannot reproduce this issue with D::C 1.15 or 1.20 or 1.23 or 1.29 (latest). Please provide the output of the commands `perl -V` and `cover -v` from your environment.
Thomas

**Comment by tomk3003** [comment] 2018-03-14 09:12
The output above was generated with Strawberry perl 5.22.2 and D::C 1.23.
I just rechecked (exact same test just switched to other SP version) with SP 5.26.1 and D::C 1.29 and now coverage is ok, that is: both tests get a 100% coverage. I guess this can be closed then.
Thomas

**Comment by pjcj** [comment] 2018-07-09 17:57
@tomk3003 Thanks very much for your report.  Let's put it down to some sort of problem with Strawberry 5.22.2 or something then.

@ikg1hd Thanks very much for the analysis - it's very much appreciated.

Closing as recommended.

**Closed by pjcj** 2018-07-09 17:57 UTC
