### ISSUE TITLE
gcov2perl ignores switch statements.

### ISSUE THREAD

**Issue by JRaspass** [pjcj/Devel--Cover#74] opened 2013-12-05 22:02 UTC
Is there some technical limitation that prevents gcov2perl from converting more than two branches? My naive reaction is, Perl has given/when, D::C must support more than two branches. But I appreciate is might not be that easy.

**Comment by pjcj** [comment] 2017-09-11 22:27
Yes, it is really a technical limitation.  The problem is that at a low level, perl only supports two branches, but C supports multiple branches.

Converting the multiple C branches to the two perl branches seems that it would be confusing.  The other way might be more sensible, as the html_minimal report tries to do.  But to do it properly would require an infrastructure which would never be used for Perl code, and I'm not sure that's worthwhile.

To be clear, I'd be happy to include it if someone else were to do the work, but realistically it's probably not far enough up my TODO list that I'll ever get to it.

So thanks very much for your report, and sorry it's taken so long for me to reply.  (That in itself rather shows that I'm probably never going to fix this myself.)  I'll close this ticket.

**Closed by pjcj** 2017-09-11 22:27 UTC
