### ISSUE TITLE
Coverage problems with string eval

### ISSUE THREAD

**Issue by Eckankar** [pjcj/Devel--Cover#145] opened 2015-10-12 15:18 UTC
In trying to research the underlying problem for #31, @ksmadsen and I found that `Devel::Cover` doesn't appear to provide correct coverage on string `eval`s, even if they use line directives to indicate their location.

Running a coverage test on the following code exhibits the problem.

``` perl
#!/usr/bin/env perl
use 5.016;
use warnings;

my $i = 1;

if ($i == 2) {
    print STDERR "hello\n";
} else {
    print STDERR "goodbye\n";
}

eval {
#line 15 "foo.pl"
if ($i == 2) {
    print STDERR "hello\n";
} else {
    print STDERR "goodbye\n";
}
};

eval <<'EOF';
#line 24 "foo.pl"
if ($i == 2) {
    print STDERR "hello\n";
} else {
    print STDERR "goodbye\n";
}
EOF
```

which gives the coverage output:

![Coverage output for the above program](http://i.imgur.com/gwfOna3.png)

The output shows that the coverage analysis is done correctly on both the regular branch and the sub `eval`, but omitted on the string `eval`.

Resolving this should hopefully resolve #31.

**Comment by pjcj** [comment] 2017-09-07 19:58
Sorry to take so long in replying to this.  Fundamentally though, the problem is that I can't collect coverage for string evals unless they create a sub, and then I can collect coverage for that sub.

s/can't/don't know how to/ I suppose, because the problem is that I have no way at the moment to get hold of the optree for the evalled string.

```
$ perl -Mblib -MDevel::Cover::Op tests/eval4

Devel::Cover 1.26: Collecting coverage data for branch, condition, pod, statement, subroutine and time.
Selecting packages matching:
Ignoring packages matching:
    blib
    \wB\w
    ^t/
    \.t$
    ^test\.pl$
Ignoring packages in:
    /cover/perls/plenv_versions/cpancover/lib/perl5/site_perl/5.26.0/x86_64-linux
    /cover/perls/plenv_versions/cpancover/lib/perl5/site_perl/5.26.0
    /cover/perls/plenv_versions/cpancover/lib/perl5/5.26.0/x86_64-linux
    /cover/perls/plenv_versions/cpancover/lib/perl5/5.26.0
goodbye
goodbye
goodbye
p  0x343b8a0               <@> leave[1 ref] vKP/REFC ->(end)
1  0x343ce48                  <0> enter ->2
2  0x2781408  s[1]            <;> nextstate(main 19 eval4:5) v ->3
5  0x2781468                  <2> sassign vKS/2 ->6
3  0x27814b0                     <$> const(IV 1) s ->4
4  0x27814f0                     <0> padsv[$i:19,34] sRM*/LVINTRO ->5
6  0x343beb0  s[1]            <;> nextstate(main 20 eval4:7) v ->7
-  0x343bf10                  <1> null vK/1 ->j
a  0x343bf50  b[,1]              <|> cond_expr(other->b) vK/1 ->1b
9  0x343b818                        <2> eq sK/2 ->a
7  0x27813d0                           <0> padsv[$i:19,34] s ->8
8  0x343b860                           <$> const(IV 2) s ->9
i  0x343b620                        <@> leave vK ->j
b  0x343bf98                           <0> enter v ->c
c  0x343b668                           <;> nextstate(main 22 eval4:8) v ->d
h  0x343b6c8                           <@> print vKS ->i
d  0x343b798                              <0> pushmark s ->e
f  0x343b758                              <1> rv2gv sKR/STRICT,1 ->g
e  0x343b7d8                                 <$> gv(*STDERR) s ->f
g  0x343b710                              <$> const(PV "hello\n") s ->h
1i 0x343c008                        <@> leave vKP ->j
1b 0x343bfd0                           <0> enter v ->1c
1c 0x343c050  s[1]                     <;> nextstate(main 24 eval4:10) v ->1d
1h 0x343c0b0                           <@> print vKS ->1i
1d 0x343b5a0                              <0> pushmark s ->1e
1f 0x343b560                              <1> rv2gv sKR/STRICT,1 ->1g
1e 0x343b5e0                                 <$> gv(*STDERR) s ->1f
1g 0x343b510                              <$> const(PV "goodbye\n") s ->1h
j  0x343cf38  s[1]            <;> nextstate(main 26 eval4:13) v ->k
l  0x343d020                  <@> leavetry vK ->m
k  0x343cf98                     <|> entertry(other->l) vK ->q
q  0x343d068  s[1]               <;> nextstate(main 27 eval4:15) v ->r
-  0x343d0c8                     <1> null vK/1 ->l
u  0x343b920  b[,1]                 <|> cond_expr(other->v) vK/1 ->13
t  0x343bde0                           <2> eq sK/2 ->u
r  0x343be68                              <0> padsv[$i:19,34] s ->s
s  0x343be28                              <$> const(IV 2) s ->t
12 0x343bbe8                           <@> leave vK ->l
v  0x343b980                              <0> enter v ->w
w  0x343bc30                              <;> nextstate(main 29 eval4:16) v ->x
11 0x343bc90                              <@> print vKS ->12
x  0x343bd60                                 <0> pushmark s ->y
z  0x343bd20                                 <1> rv2gv sKR/STRICT,1 ->10
y  0x343bda0                                    <$> gv(*STDERR) s ->z
10 0x343bcd8                                 <$> const(PV "hello\n") s ->11
1a 0x343b9f0                           <@> leave vKP ->l
13 0x343b9b8                              <0> enter v ->14
14 0x343ba38  s[1]                        <;> nextstate(main 31 eval4:18) v ->15
19 0x343ba98                              <@> print vKS ->1a
15 0x343bb68                                 <0> pushmark s ->16
17 0x343bb28                                 <1> rv2gv sKR/STRICT,1 ->18
16 0x343bba8                                    <$> gv(*STDERR) s ->17
18 0x343bae0                                 <$> const(PV "goodbye\n") s ->19
m  0x343ce90  s[1]            <;> nextstate(main 34 eval4:22) v ->n
o  0x343cfe0                  <1> entereval[t2018] vK/1 ->p
n  0x343cef0                     <$> const(PV "#line 24 \"tests/eval4\"\nif ($i == 2) {\n    print STDERR \"hello\\n\";\n} else {\n    print STDERR \"goodbye\\n\";\n}\n") s ->o
Devel::Cover: Writing coverage database to /cover/Devel--Cover/cover_db/runs/1504812364.31303.40425
---------------------------- ------ ------ ------ ------ ------ ------ ------
File                           stmt   bran   cond    sub    pod   time  total
---------------------------- ------ ------ ------ ------ ------ ------ ------
tests/eval4                    86.6   50.0    n/a  100.0    n/a  100.0   80.9
Total                          86.6   50.0    n/a  100.0    n/a  100.0   80.9
---------------------------- ------ ------ ------ ------ ------ ------ ------

```

You can see at the end that the eval is not compiled into the optree.

So I'm going to close this as wontfix, but I have added the script you provided as a test and if we ever come up with some way of getting coverage on the evalled string then it would be great to add it.

The changes are in 52b18d3b281611fb2b8a7e1bcc938f6b9457c33d, and I have also added you to the Contributors file.  Please free to amend or delete this entry as you see fit.

Thanks again for your report and the useful test file, and sorry again that it took me so long to reply.

**Closed by pjcj** 2017-09-07 19:58 UTC
Labels: status: won't fix now
