### ISSUE TITLE
Line only declaring variables reported as unexercised

### ISSUE THREAD

**Issue by jkeenan** [pjcj/Devel--Cover#129] opened 2015-07-03 02:00 UTC
The constructor for List::Compare (https://github.com/jkeenan/list-compare/blob/2614b2c2f1e4c10fe297acbbea60cf30e457e7af/lib/List/Compare.pm) starts with a couple of lines that simply declare variables..

``` perl
sub new {
    my $class = shift;
    my (@args, $unsorted, $accelerated);
    my ($argument_error_status, $nextarg, @testargs);
...
```

Each of the variables in the third line is used later in new(); removing any of them causes a compilation failure.  So I would presume that the third line is exercised -- covered -- every time new() is called in List::Compare's test suite.

When I ran Devel::Cover (version 1.18, perl-5.20.1) over List::Compare (version 0.53), I was surprised to see that that line was reported uncovered in the test suite.  Excerpt from the text version of the coverage report:

```
11                                             sub new {
12           212                  212 1622793       my $class = shift;
13           212                         173       my (@args, $unsorted, $accelerated);
14    ***      0                           0       my ($argument_error_status, $nextarg, @testargs);
```

So I tested new() 212 times -- but no coverage was reported for line 14.  This surprised me, as (a) I always thought I had 100% statement coverage of this file, and (b) I was doing extensive refactoring of List::Compare earlier this year, at which time I'm certain I would have run Devel::Cover on it at least once.

I played around with this a little.  If I pulled the declaration of $argument_error_status and $nextarg out of line 14 and put them into line 13, line 14 would then only hold the declaration for @testargs -- but the line was still reported as uncovered.  It was only when I pulled the declaration of @testargs out of line 14 and put it into line 13 that I returned to 100% statement coverage for this file.

```
11                                             sub new {
12           212                  212 1629714       my $class = shift;
13           212                         181       my (@args, $unsorted, $accelerated, $argument_error_status, $nextarg, @testargs);
14           212    100    100           698       if (@_ == 1 and (ref($_[0]) eq 'HASH')) {
```

Is this expected behavior?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment] 2015-07-03 02:30
I found a similar lack of coverage at one other point in List-Compare.  Inside lib/List/Compare/Base/_Auxiliary, I had this code, one line of which was reported unexercised:
```
74                                             sub _validate_2_seenhashes {
75            27                   27     20       my ($refL, $refR) = @_;
76            27                          20       my (%seenL, %seenR);
77    ***      0                           0       my (%badentriesL, %badentriesR);
78            27                          47       foreach (keys %$refL) {
```
As was the case before, when I combined the two lines which simply declared variables into just one, statement coverage returned to 100%.
```
74                                             sub _validate_2_seenhashes {
75            27                   27     22       my ($refL, $refR) = @_;
76            27                          19       my (%seenL, %seenR, %badentriesL, %badentriesR);
77            27                          54       foreach (keys %$refL) {
```

**Comment by pjcj** [comment] 2015-07-05 20:51
Hello Jim, and thanks for your report.

I'm having trouble reproducing this.  Every example I put together seems to be working correctly.  Do you happen to have a small failing example?

**Comment by jkeenan** [comment] 2015-07-05 22:51
http://thenceforward.net/perl/misc/Devel--Cover-issue-129.tar.gz

**Comment by pjcj** [comment] 2015-08-03 22:46
I suspect this is the same as #132.

**Comment by pjcj** [comment] 2017-05-11 16:42
I believe this is now fixed in the latest releases. Jim, if that turns out not to be the case, please feel free to reopen this. Thanks very much for the report and test case!

**Closed by pjcj** 2017-05-11 16:42 UTC
Labels: needs investigation
