### ISSUE TITLE
Error related to invalid JSON?

### ISSUE THREAD

**Issue by frioux** [pjcj/Devel--Cover#131] opened 2015-07-09 16:26 UTC
This is a shot in the dark, but I figure I might as well put it down before I forget about seeing this.  I just saw this on travisci a few minutes ago:

```
Can't read /home/travis/build/bluefeet/Web-Starch/cover_db/digests with JSON::PP: garbage after JSON object, at character offset 12529 (before "erlbrew/perls/5.10/l...") at /home/travis/perl5/perlbrew/perls/5.10/lib/site_perl/5.10.1/x86_64-linux/Devel/Cover/DB/IO/JSON.pm line 40.
```

No idea what caused it or any more than that, as I don't have access to the actual files, and seems very spurious.  If I see it again I'll update here.

**Comment by pjcj** [comment] 2015-08-03 22:32
Thanks very much for reporting this.  It's not something I have seen before, but I'll leave this ticket open in case we can gather any more information.

**Comment by dolmen** [comment] 2015-09-11 08:38
This looks like the locking issue reported in #73 and #90.

@frioux: do you use parrallel testing?

**Comment by frioux** [comment] 2015-09-11 16:18
No; that tends to cause a lot of problems so I do not.

**Comment by frioux** [comment] 2016-04-12 04:40
More examples: https://travis-ci.org/frioux/Log-Contextual/jobs/122424701, https://travis-ci.org/frioux/Log-Contextual/jobs/122424900

**Comment by mephinet** [comment] 2016-10-07 08:48
My observation, in case it helps:
We are running the identical set of unittests with Devel::Cover 1.23 on three different machines:
* RHEL 5.10 with Perl 5.20.2
* RHEL 6.5 with Perl 5.20.2
* RHEL 7.2 with Perl 5.24.0

I regularly see these issues, but only on the third machine. They all have JSON 2.90 installed, to Sereal, and no tests are run in parallel.

**Comment by pjcj** [comment] 2017-09-14 22:32
We're unlikely to make any progress here as things stand, but I have just reworked all of the IO modules to fix problems _similar_ to this.  So I'm going to close this ticket, but if it turns out to be a problem after the next release, please feel free to reopen it, especially if there is any way to reliably reproduce it.

Thanks to all involved.

**Closed by pjcj** 2017-09-14 22:32 UTC
Labels: status: blocked
